presubmits:
  GoogleCloudPlatform/gcs-fuse-csi-driver:
  - name: pull-gcs-fuse-csi-driver-e2e-test
    branches:
    - main
    always_run: true         # Run for every PR, or only when requested.
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    decorate: true
    cluster: build-gke-managed-storage
    spec:
      serviceAccountName: prowjob-default-sa
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20260316-e86cefa561-1.32
        command:
        - runner.sh
        args:
        - test/e2e/run-e2e-ci.sh
        env:
        - name: GCE_PD_BOSKOS_RESOURCE_TYPE
          value: "oss-boskos-e2e-test-project"
        - name: USE_GKE_MANAGED_DRIVER
          value: "false"
        - name: BOSKOS_URL
          value: "http://boskos.boskos.svc.cluster.local"
        - name: USER
          value: "prow"
        # Remove the "Feature" tag from the tests to run the tests in pre-submits. Once the tests are stable we can update the test-skip here
        - name: TEST_SKIP
          value: '"should.succeed.in.performance.test|Feature:.workload-identity-federation|Feature:.OIDC|Feature:.GCSFuse-PDCSI"'
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 8Gi
            ephemeral-storage: 6Gi
          limits:
            memory: 8Gi
            ephemeral-storage: 10Gi
      volumes:
      - name: ssh
        secret:
          defaultMode: 256
          secretName: ssh-key-secret
          items:
          - key: ssh-private
            path: google_compute_engine
          - key: ssh-public
            path: google_compute_engine.pub