---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hook-ghapp
  namespace: default
  labels:
    app: hook-ghapp
spec:
  replicas: 6
  selector:
    matchLabels:
      app: hook-ghapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hook-ghapp
    spec:
      serviceAccountName: hook
      terminationGracePeriodSeconds: 180
      containers:
      - name: hook
        image: gcr.io/k8s-prow/hook:v20211109-c52470a888
        imagePullPolicy: Always
        args:
        - --webhook-path=/ghapp-hook
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --dry-run=false
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --github-app-id=$(GITHUB_APP_ID)
        - --github-app-private-key-path=/etc/github/cert
        - --github-enabled-org=repo-does-not-exist
        - --github-enabled-org=chaotoppicks
        - --github-enabled-org=looker
        - --github-enabled-org=GoogleCloudPlatform
        - --github-enabled-org=kubeflow
        - --github-enabled-org=google
        - --github-enabled-org=googleforgames
        - --github-enabled-repo=grpc-ecosystem/grpc-httpjson-transcoding
        env:
        # Use KUBECONFIG envvar rather than --kubeconfig flag in order to provide multiple configs to merge.
        - name: KUBECONFIG
          value: "/etc/kubeconfig/config-20211108:/etc/build-bms-oracle-team/kubeconfig:/etc/build-looker-32/kubeconfig:/etc/build-looker-16/kubeconfig:/etc/build-looker-int-test/kubeconfig:/etc/build-blueprints/kubeconfig:/etc/build-elcarro/kubeconfig:/etc/build-looker-private/kubeconfig:/etc/build-kubeflow/kubeconfig"
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: ghapp-token
              key: appid
        ports:
        - name: http
          containerPort: 8888
        - name: metrics
          containerPort: 9090
        volumeMounts:
        - mountPath: /etc/build-bms-oracle-team
          name: build-bms-oracle-team
          readOnly: true
        - mountPath: /etc/build-looker-32
          name: build-looker-32
          readOnly: true
        - mountPath: /etc/build-looker-16
          name: build-looker-16
          readOnly: true
        - mountPath: /etc/build-looker-int-test
          name: build-looker-int-test
          readOnly: true
        - mountPath: /etc/build-blueprints
          name: build-blueprints
          readOnly: true
        - mountPath: /etc/build-elcarro
          name: build-elcarro
          readOnly: true
        - mountPath: /etc/build-looker-private
          name: build-looker-private
          readOnly: true
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: ghapp-token
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
        - name: build-kubeflow
          mountPath: /etc/build-kubeflow
          readOnly: true
        resources:
          requests: # peak usage sampled by most recent usages of hook
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 600
      volumes:
      - name: build-bms-oracle-team
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-bms-oracle-team
      - name: build-looker-32
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-looker-32
      - name: build-looker-16
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-looker-16
      - name: build-looker-int-test
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-looker-int-test
      - name: build-blueprints
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-blueprints
      - name: build-elcarro
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-elcarro
      - name: build-looker-private
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-looker-private
      - name: hmac
        secret:
          secretName: ghapp-hmac-token
      - name: ghapp-token
        secret:
          secretName: ghapp-token
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      - name: plugins
        configMap:
          name: plugins
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
      - name: build-kubeflow
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-kubeflow
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hook-ghapp
  name: hook-ghapp
  namespace: default
spec:
  selector:
    app: hook-ghapp
  ports:
  - name: main
    port: 8888
  - name: metrics
    port: 9090
  type: NodePort
