---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tide
  namespace: default
  labels:
    app: tide
spec:
  replicas: 1 # Do not scale up.
  selector:
    matchLabels:
      app: tide
  template:
    metadata:
      labels:
        app: tide
    spec:
      serviceAccountName: tide
      containers:
      - name: tide
        image: gcr.io/k8s-prow/tide:v20210913-b6578706d1
        args:
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --dry-run=false
        - --history-uri=gs://oss-prow/tide-history.json
        - --status-path=gs://oss-prow/tide-status-checkpoint.yaml
        - --github-token-path=/etc/github/oauth
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        ports:
        - name: http
          containerPort: 8888
        - name: metrics
          containerPort: 9090
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        resources:
          # Tide does inrepoconfig prowjob lookup, which is very
          # disk and cpu intensive. This is even worse when there
          # is a spike of PRs going on.
          # The node has 7.91CPU in total, set requests and limits,
          # so that tide uses a single node.
          requests:
            cpu: 7
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      tolerations:
      - key: "highcpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      nodeSelector:
        highcpu: "true"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tide
  name: tide
  namespace: default
spec:
  selector:
    app: tide
  ports:
  - name: main
    port: 80
    targetPort: 8888
  - name: metrics
    port: 9090
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tide
  namespace: default
  annotations:
    "iam.gke.io/gcp-service-account": "oss-prow@oss-prow.iam.gserviceaccount.com"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tide
  namespace: default
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - create
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tide
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tide
subjects:
- kind: ServiceAccount
  name: tide
