{
 "title": "GitHub Cache",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "token",
    "label": "token",
    "query": "label_values(github_request_duration_count{job=\"ghproxy\"}, token_hash)"
   },
   {
    "name": "path",
    "label": "path",
    "query": "label_values(github_request_duration_count{job=\"ghproxy\"}, path)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "label_values(github_request_duration_count{job=\"ghproxy\"}, status)"
   },
   { "name": "range", "label": "range", "query": "3h,1h,30m,15m,10m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Cache Requests (per hour)",
   "type": "graph",
   "description": "Count of cache requests of each cache mode over the last hour.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses[1h])) by (mode)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]))",
     "legendFormat": "(No Cost)"
    }
   ]
  },
  {
   "title": "Cache Efficiency",
   "type": "graph",
   "description": "Percentage of cacheable requests that are fulfilled for free.\nNo cost modes are \"COALESCED\" and \"REVALIDATED\".\nCacheable modes include the no cost modes, \"CHANGED\" and \"MISS\".",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h])) \n/ sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED|MISS|CHANGED\"}[1h]))",
     "legendFormat": "Efficiency"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ghcache_disk_used) without (instance,pod)",
     "legendFormat": "GB Used"
    },
    {
     "expr": "avg(ghcache_disk_free) without (instance,pod)",
     "legendFormat": "GB Free"
    }
   ]
  },
  {
   "title": "API Tokens Saved: Last hour",
   "type": "singlestat",
   "description": "The number of no cost requests in the last hour.\nThis includes both \"COALESCED\" and \"REVALIDATED\" modes.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]))"
    }
   ]
  },
  {
   "title": "API Tokens Saved: Last 7 days",
   "type": "singlestat",
   "description": "The number of no cost requests in the last 7 days.\nThis includes both \"COALESCED\" and \"REVALIDATED\" modes.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[7d]))"
    }
   ]
  },
  {
   "title": "Token Usage",
   "type": "graph",
   "description": "GitHub token usage by token identifier and API version.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(github_token_usage) by (api_version, token_hash), \"token_hash_short\", \"$1\", \"token_hash\", \"([a-z0-9]{5})(.*)\")",
     "legendFormat": "{{api_version}}:{{token_hash_short}}"
    }
   ]
  },
  {
   "title": "Request Rates: Overview by status with ${range}",
   "type": "graph",
   "description": "GitHub request rates by status.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_request_duration_count{job=\"ghproxy\"}[${range}])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Rates: Overview by path for ${status} with ${range}",
   "type": "graph",
   "description": "GitHub request rates by path.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_request_duration_count{status=\"${status}\",job=\"ghproxy\"}[${range}])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Rates: ${token}, ${path}, and ${status} with ${range}",
   "type": "graph",
   "description": "GitHub request rates by token identifier, path and status.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(github_request_duration_count{job=\"ghproxy\", token_hash=\"${token}\", path=\"${path}\", status=\"${status}\"}[${range}])) by (token_hash, path, status), \"token_hash_short\", \"$1\", \"token_hash\", \"([a-z0-9]{5})(.*)\")",
     "legendFormat": "{{status}}:{{token_hash_short}}:{{path}}"
    }
   ]
  },
  {
   "title": "Latency Distribution Overview with ${range}",
   "type": "graph",
   "description": "histogram_quantile(<phi>, sum(rate(github_request_duration_bucket{job=\"ghproxy\"}[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(github_request_duration_bucket{job=\"ghproxy\"}[5m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(github_request_duration_bucket{job=\"ghproxy\"}[5m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(github_request_duration_bucket{job=\"ghproxy\"}[5m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Latency Distribution for ${token}, ${path}, and ${status} with ${range}",
   "type": "graph",
   "description": "histogram_quantile(<phi>, sum(rate(github_request_duration_bucket{job=\"ghproxy\", token_hash=~\"${token}\", path=~\"${path}\", status=~\"${status}\"}[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(github_request_duration_bucket{job=\"ghproxy\", token_hash=\"${token}\", path=\"${path}\", status=\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(github_request_duration_bucket{job=\"ghproxy\", token_hash=\"${token}\", path=\"${path}\", status=\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(github_request_duration_bucket{job=\"ghproxy\", token_hash=\"${token}\", path=\"${path}\", status=\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "GitHub Request Timeout Rates: Overview by path with ${range}",
   "type": "graph",
   "description": "GitHub request timeout rates by path.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_request_timeouts_bucket[${range}])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}