presubmits:
  bazelbuild/rules_k8s:
  - name: pull-rules-k8s-e2e
    cluster: gke_rules-k8s_us-central1-f_testing
    always_run: true
    decorate: true
    spec:
      serviceAccount: prowjob-default-sa
      containers:
      - image: gcr.io/rules-k8s/gcloud-bazel:v20210501-v0.6-28-gaf2e97d
        args:
        - bash
        - -c
        - |
          gcloud container clusters get-credentials testing --zone=us-central1-f --project=rules-k8s \
          && echo "startup --host_jvm_args=-Duser.name=prow" > /root/.bazelrc \
          && ./test-e2e.sh
        env:
        - name: USER
          value: prow
